<a href="https://colab.research.google.com/github/naumankhokhar/sp500-ml-clustering-portfolio-optimization/blob/dev/group_coursework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This is the start of the fresh work. 6:56-TUE- 21/4/26

In [ ]:
import pandas as pd

### Step 1: Extract S&P 500 Tickers

I will use `pandas.read_html` to extract the S&P 500 component list from Wikipedia. This requires the `lxml` library, so I'll install it first if it's not already available.

In [ ]:
# Install required packages
!pip install yfinance yahoofinancials lxml html5lib --quiet

import pandas as pd

url = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"

# Add User-Agent header to mimic a browser request
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}
tables = pd.read_html(url, storage_options=headers)

df = tables[0]  # first table on the page
df.head()

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989

### Step 1.1: Save S&P 500 Tickers to CSV

Now that we have extracted the S&P 500 list into a DataFrame, I will save it to a CSV file named `sp500_tickers.csv`.

In [ ]:
# Save the DataFrame to a CSV file
df.to_csv('sp500_tickers.csv', index=False)

print("S&P 500 tickers saved to 'sp500_tickers.csv'.")

# Display the first few rows of the DataFrame to confirm
display(df.head())

S&P 500 tickers saved to 'sp500_tickers.csv'.

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989

### Step 2: Load S&P 500 Tickers Daily Market Performance

I will use the `yfinance` package to download the daily market performance data for the S&P 500 tickers for the period 01-01-2022 to 01-01-2025. I'll first extract the 'Symbol' column from our `df` to get the list of tickers.

In [ ]:
import yfinance as yf

# Extract the 'Symbol' column to get the list of tickers
sp500_tickers = df['Symbol'].tolist()

start_date = '2022-01-01'
end_date = '2025-01-01'

print(f"Downloading daily market performance for {len(sp500_tickers)} tickers from {start_date} to {end_date}...")

# Download data for all S&P 500 tickers
data = yf.download(sp500_tickers, start=start_date, end=end_date)

print("Data downloaded successfully. Displaying the first 5 rows of the 'Adj Close' prices:")
display(data['Adj Close'].head())

/tmp/ipykernel_21630/3139829422.py:12: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(sp500_tickers, start=start_date, end=end_date)
[                       0%                       ]

Downloading daily market performance for 503 tickers from 2022-01-01 to 2025-01-01...

[*********************100%***********************]  503 of 503 completed
ERROR:yfinance:
4 Failed downloads:
ERROR:yfinance:['BF.B']: YFPricesMissingError('possibly delisted; no price data found  (1d 2022-01-01 -> 2025-01-01)')
ERROR:yfinance:['BRK.B']: YFTzMissingError('possibly delisted; no timezone found')
ERROR:yfinance:['SNDK', 'Q']: YFPricesMissingError('possibly delisted; no price data found  (1d 2022-01-01 -> 2025-01-01) (Yahoo error = "Data doesn\'t exist for startDate = 1641013200, endDate = 1735707600")')

Data downloaded successfully. Displaying the first 5 rows of the 'Adj Close' prices:

Ticker      BF.B  BRK.B   Q  SNDK
Date
2022-01-03   NaN    NaN NaN   NaN
2022-01-04   NaN    NaN NaN   NaN
2022-01-05   NaN    NaN NaN   NaN
2022-01-06   NaN    NaN NaN   NaN
2022-01-07   NaN    NaN NaN   NaN